'use client';

import { useEffect, useState } from 'react';
import { invoke } from '@tauri-apps/api/core';
import { AlertTriangle, CheckCircle2, Database, FileSearch, FolderOpen, Loader2 } from 'lucide-react';
import { toast } from 'sonner';
import { useLanguage } from '@/contexts/LanguageContext';

type Preview = {sourcePath:string;targetPath:string;categories:Array<{key:string;rows:number}>;audioReferences:number;missingAudioReferences:number;excludedRows:number;excludedItems:string[]};
type Report = {insertedRows:number;skippedExistingRows:number;preservedAudioReferences:number;missingAudioReferences:number};
const labels:Record<string,[string,string]>={meetings:['会议基础信息','Meetings'],rawTranscripts:['原始文字稿','Raw transcripts'],transcriptVersions:['原始 / 聚类版本','Original / clustered versions'],aiRefinements:['AI 优化文字稿','AI-refined transcripts'],meetingNotes:['会议笔记','Meeting notes'],publicDocuments:['智能记录 / 纪要 / 讲话文档','Smart records / summaries / speech documents'],recordBlocks:['公共智能记录段落','Public smart-record blocks'],tags:['会议标签','Meeting tags']};

export function DataMigrationSettings(){
  const {locale}=useLanguage();const zh=locale==='zh-CN';
  const [sourcePath,setSourcePath]=useState('');const [preview,setPreview]=useState<Preview|null>(null);const [report,setReport]=useState<Report|null>(null);
  const [loading,setLoading]=useState(false);const [importing,setImporting]=useState(false);const [includeAudioReferences,setIncludeAudioReferences]=useState(false);const [confirmed,setConfirmed]=useState(false);
  useEffect(()=>{invoke<string|null>('api_get_default_legacy_calmee_source').then(path=>path&&setSourcePath(path)).catch(()=>undefined);},[]);
  const selectSource=async()=>{const path=await invoke<string|null>('api_select_legacy_calmee_source');if(path){setSourcePath(path);setPreview(null);setReport(null);setConfirmed(false);}};
  const loadPreview=async()=>{if(!sourcePath)return;setLoading(true);setReport(null);setConfirmed(false);try{setPreview(await invoke<Preview>('api_preview_legacy_calmee_import',{sourcePath}));}catch(error){setPreview(null);toast.error(zh?'无法预览旧数据':'Could not preview old data',{description:String(error)});}finally{setLoading(false);}};
  const runImport=async()=>{if(!preview||!confirmed)return;setImporting(true);try{setReport(await invoke<Report>('api_import_legacy_calmee_data',{options:{sourcePath:preview.sourcePath,includeAudioReferences}}));toast.success(zh?'公共数据导入完成':'Public data import completed');}catch(error){toast.error(zh?'导入失败，所有变更已回滚':'Import failed; all changes were rolled back',{description:String(error)});}finally{setImporting(false);}};
  return <div className="mt-6 space-y-5">
    <section className="rounded-2xl border border-violet-100 bg-white p-6 shadow-sm">
      <div className="flex items-start gap-4"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-violet-100 text-violet-700"><Database className="h-5 w-5"/></span><div><h2 className="text-lg font-semibold text-slate-900">{zh?'从旧 CalMee 数据导入':'Import from old CalMee data'}</h2><p className="mt-1 text-sm leading-6 text-slate-500">{zh?'旧数据库始终只读。CalMee 会先显示可导入数量，并只把白名单中的公共会议数据写入开源版专属数据库。':'The old database stays read-only. CalMee previews counts first and writes only allowlisted public meeting data to the community database.'}</p></div></div>
      <div className="mt-5 rounded-xl border border-slate-200 bg-slate-50 p-4"><p className="text-xs font-semibold text-slate-600">{zh?'来源数据库（只读）':'Source database (read-only)'}</p><p className="mt-2 break-all font-mono text-xs leading-5 text-slate-500">{sourcePath||(zh?'尚未选择':'Not selected')}</p><div className="mt-3 flex gap-2"><button type="button" onClick={()=>void selectSource()} className="flex h-9 items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 text-xs font-medium text-slate-700"><FolderOpen className="h-4 w-4"/>{zh?'选择文件':'Choose file'}</button><button type="button" onClick={()=>void loadPreview()} disabled={!sourcePath||loading} className="flex h-9 items-center gap-2 rounded-lg bg-violet-600 px-3 text-xs font-medium text-white disabled:opacity-40">{loading?<Loader2 className="h-4 w-4 animate-spin"/>:<FileSearch className="h-4 w-4"/>}{zh?'只读预览':'Preview read-only'}</button></div></div>
    </section>
    {preview&&<section className="rounded-2xl border border-violet-100 bg-white p-6 shadow-sm"><h3 className="font-semibold text-slate-900">{zh?'导入预览':'Import preview'}</h3><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{preview.categories.map(item=><div key={item.key} className="rounded-xl border border-slate-100 bg-slate-50 p-3"><p className="text-2xl font-semibold text-slate-800">{item.rows}</p><p className="mt-1 text-xs leading-5 text-slate-500">{labels[item.key]?.[zh?0:1]??item.key}</p></div>)}</div>
      <div className="mt-5 space-y-2 rounded-xl border border-amber-200 bg-amber-50 p-4 text-xs leading-5 text-amber-900"><div className="flex items-center gap-2 font-semibold"><AlertTriangle className="h-4 w-4"/>{zh?'明确排除':'Always excluded'}</div><p>{preview.excludedItems.join(' · ')}</p><p>{zh?`源库中检测到 ${preview.excludedRows} 条排除范围记录；它们不会写入新库。`:`${preview.excludedRows} excluded rows were detected; they will not be copied.`}</p></div>
      <div className="mt-5 rounded-xl border border-slate-200 p-4 text-xs leading-5 text-slate-600"><p><strong>{zh?'来源：':'Source: '}</strong><span className="break-all font-mono">{preview.sourcePath}</span></p><p className="mt-2"><strong>{zh?'目标：':'Target: '}</strong><span className="break-all font-mono">{preview.targetPath}</span></p><p className="mt-2">{zh?`音频文件夹引用 ${preview.audioReferences} 条，其中 ${preview.missingAudioReferences} 条路径已不存在。不会自动复制音频。`:`${preview.audioReferences} audio folder references; ${preview.missingAudioReferences} paths are missing. Audio is never copied automatically.`}</p></div>
      <label className="mt-4 flex items-start gap-3 rounded-xl border border-slate-200 p-4 text-sm text-slate-700"><input type="checkbox" checked={includeAudioReferences} onChange={event=>setIncludeAudioReferences(event.target.checked)} className="mt-1"/><span>{zh?'保留仍然存在的音频文件夹引用（只保存路径，不复制文件；缺失路径会跳过）':'Keep audio folder references that still exist (paths only; no files are copied and missing paths are skipped)'}</span></label>
      <label className="mt-3 flex items-start gap-3 rounded-xl border border-violet-200 bg-violet-50 p-4 text-sm text-violet-900"><input type="checkbox" checked={confirmed} onChange={event=>setConfirmed(event.target.checked)} className="mt-1"/><span>{zh?'我已核对来源、目标和排除项，并确认开始事务化导入。重复记录保留目标库现有版本。':'I reviewed the source, target, and exclusions. Import transactionally and keep existing target records on duplicates.'}</span></label>
      <button type="button" onClick={()=>void runImport()} disabled={!confirmed||importing} className="mt-4 flex h-10 items-center gap-2 rounded-xl bg-violet-600 px-5 text-sm font-medium text-white disabled:opacity-40">{importing&&<Loader2 className="h-4 w-4 animate-spin"/>}{zh?'开始安全导入':'Start safe import'}</button>
    </section>}
    {report&&<section className="flex items-start gap-3 rounded-2xl border border-emerald-200 bg-emerald-50 p-5 text-sm text-emerald-900"><CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0"/><p>{zh?`已写入 ${report.insertedRows} 条；跳过 ${report.skippedExistingRows} 条重复记录；保留 ${report.preservedAudioReferences} 条音频引用；跳过 ${report.missingAudioReferences} 条缺失引用。`:`Inserted ${report.insertedRows}; skipped ${report.skippedExistingRows} duplicates; preserved ${report.preservedAudioReferences} audio references; skipped ${report.missingAudioReferences} missing references.`}</p></section>}
  </div>;
}
