"use client";

import { useEffect, useMemo, useState } from 'react';
import { invoke } from '@tauri-apps/api/core';
import { CalendarDays, Check, Link2Off, Loader2, Search } from 'lucide-react';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { ProductButton, ProductEmptyState, ProductInput } from '@/components/ui/ProductControls';
import { toast } from 'sonner';
import { useLanguage } from '@/contexts/LanguageContext';
import { reportTechnicalError, toUserFacingError } from '@/lib/feedback';

type CalendarEvent = { id:string; title:string; startAt:string; endAt?:string; calendarId?:string; calendarName?:string; source:string; location?:string; meetingId?:string };
type CalendarCollection = { id:string; name:string; color:string };

export function CalendarLinkDialog({ open, onOpenChange, meetingId, meetingTime, currentEventId, onLinked }: { open:boolean; onOpenChange:(open:boolean)=>void; meetingId:string; meetingTime?:string; currentEventId?:string|null; onLinked:(event:CalendarEvent|null)=>void }) {
  const { locale }=useLanguage();const zh=locale==='zh-CN';
  const [events,setEvents]=useState<CalendarEvent[]>([]);const [collections,setCollections]=useState<CalendarCollection[]>([]);const [query,setQuery]=useState('');const [loading,setLoading]=useState(false);
  useEffect(()=>{if(!open)return;setLoading(true);const center=meetingTime?new Date(meetingTime):new Date();const start=new Date(center);start.setDate(start.getDate()-30);const end=new Date(center);end.setDate(end.getDate()+30);Promise.all([invoke<CalendarEvent[]>('api_get_calendar_events',{startAt:start.toISOString(),endAt:end.toISOString()}),invoke<CalendarCollection[]>('api_get_calendar_collections')]).then(([items,cals])=>{setEvents(items);setCollections(cals);}).catch(error=>{reportTechnicalError('calendar-link-load',error);toast.error(zh?'无法读取日程':'Could not load calendar events',{description:toUserFacingError(error,locale).message});}).finally(()=>setLoading(false));},[open,meetingTime,locale,zh]);
  const colorById=useMemo(()=>new Map(collections.map(item=>[item.id,item.color])),[collections]);
  const filtered=useMemo(()=>events.filter(event=>!query.trim()||`${event.title} ${event.calendarName||''} ${event.location||''}`.toLowerCase().includes(query.toLowerCase())),[events,query]);
  const link=async(event:CalendarEvent|null)=>{try{await invoke('api_link_meeting_calendar_event',{meetingId,eventId:event?.id||null});onLinked(event);onOpenChange(false);toast.success(event?(zh?'日程已关联':'Calendar event linked'):(zh?'已解除日程关联':'Calendar link removed'));}catch(error){reportTechnicalError('calendar-link-save',error);toast.error(zh?'无法关联日程':'Could not link calendar event',{description:toUserFacingError(error,locale).message});}};
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>{zh?'关联日程':'Link calendar event'}</DialogTitle><DialogDescription>{zh?'根据会议时间显示前后 30 天的日程。':'Showing events within 30 days of the meeting time.'}</DialogDescription></DialogHeader><div className="relative"><Search className="pointer-events-none absolute left-3 top-2.5 h-4 w-4 text-muted-foreground"/><ProductInput value={query} onChange={event=>setQuery(event.target.value)} placeholder={zh?'搜索最近 60 天的日程':'Search events from the surrounding 60 days'} className="w-full pl-9"/></div><div className="max-h-[430px] space-y-1 overflow-y-auto py-1">{loading?<div className="flex items-center justify-center gap-2 py-16 text-sm text-muted-foreground"><Loader2 className="h-4 w-4 animate-spin"/>{zh?'正在读取日程…':'Loading calendar events…'}</div>:filtered.length===0?<ProductEmptyState icon={<CalendarDays className="h-5 w-5"/>} title={zh?'没有找到日程':'No events found'} description={zh?'可以修改关键词，或者先到日历页面同步。':'Try another search or sync calendars first.'}/>:filtered.map(event=>{const linked=currentEventId===event.id;return <button key={event.id} onClick={()=>void link(event)} className={`flex w-full items-center gap-3 rounded-lg p-3 text-left transition hover:bg-accent/65 ${linked?'bg-primary/8':''}`}><span className="flex h-9 w-9 items-center justify-center rounded-lg" style={{backgroundColor:`${colorById.get(event.calendarId||'')||'#8B5CF6'}18`,color:colorById.get(event.calendarId||'')||'#8B5CF6'}}><CalendarDays className="h-4 w-4"/></span><span className="min-w-0 flex-1"><span className="block truncate text-[13px] font-medium text-foreground">{event.title}</span><span className="mt-0.5 block text-xs text-muted-foreground">{new Date(event.startAt).toLocaleString(locale)} · {event.calendarName||event.source}</span></span>{linked&&<Check className="h-4 w-4 text-primary"/>}</button>})}</div>{currentEventId&&<DialogFooter><ProductButton variant="ghost" className="text-destructive hover:text-destructive" onClick={()=>void link(null)}><Link2Off className="h-4 w-4"/>{zh?'解除关联':'Remove link'}</ProductButton></DialogFooter>}</DialogContent></Dialog>;
}
