#!/usr/bin/env python3

import hashlib
import importlib.metadata
import json
import pathlib
import re
import shutil
import sys


def safe_name(value: str) -> str:
    return re.sub(r"[^A-Za-z0-9_.-]+", "-", value).strip("-") or "unknown"


runtime_root = pathlib.Path(sys.argv[1]).resolve()
output_root = runtime_root / "third-party"
licenses_root = output_root / "licenses"
if output_root.exists():
    shutil.rmtree(output_root)
licenses_root.mkdir(parents=True)

packages = []
missing = []
for distribution in sorted(
    importlib.metadata.distributions(),
    key=lambda item: (item.metadata.get("Name") or "").lower(),
):
    metadata = distribution.metadata
    name = metadata.get("Name") or "unknown"
    classifiers = [
        value for value in (metadata.get_all("Classifier") or []) if value.startswith("License ::")
    ]
    license_expression = metadata.get("License-Expression")
    license_metadata = metadata.get("License")
    package_dir = licenses_root / f"{safe_name(name)}-{safe_name(distribution.version)}"
    copied = []
    seen = set()
    for entry in distribution.files or []:
        if not entry.name.lower().startswith(("license", "copying", "notice", "copyright")):
            continue
        source = pathlib.Path(distribution.locate_file(entry)).resolve()
        if not source.is_file() or source in seen:
            continue
        seen.add(source)
        package_dir.mkdir(parents=True, exist_ok=True)
        destination = package_dir / f"{len(copied) + 1:02d}-{safe_name(source.name)}"
        shutil.copyfile(source, destination)
        copied.append(destination.relative_to(output_root).as_posix())
    if not copied and not license_expression and not license_metadata and not classifiers:
        missing.append(f"{name}=={distribution.version}")
    packages.append({
        "name": name,
        "version": distribution.version,
        "licenseExpression": license_expression,
        "licenseMetadata": license_metadata,
        "licenseClassifiers": classifiers,
        "homepage": metadata.get("Home-page") or metadata.get("Project-URL"),
        "licenseFiles": copied,
    })

python_license = pathlib.Path(sys.base_prefix) / "lib" / f"python{sys.version_info.major}.{sys.version_info.minor}" / "LICENSE.txt"
if not python_license.is_file():
    raise SystemExit("The managed CPython distribution does not contain LICENSE.txt")
shutil.copyfile(python_license, output_root / "CPYTHON-LICENSE.txt")
if missing:
    raise SystemExit("Missing machine-readable license evidence for: " + ", ".join(missing))

inventory = {
    "schemaVersion": 1,
    "python": {
        "implementation": sys.implementation.name,
        "version": ".".join(map(str, sys.version_info[:3])),
        "licenseFile": "CPYTHON-LICENSE.txt",
    },
    "packages": packages,
}
inventory_bytes = (json.dumps(inventory, indent=2, sort_keys=True) + "\n").encode()
(output_root / "python-packages.json").write_bytes(inventory_bytes)
(output_root / "NOTICE.txt").write_text(
    "CalMee installed Python runtime third-party notices\n"
    "==================================================\n\n"
    "This directory is generated by the first-use target-native runtime installer.\n"
    "CPYTHON-LICENSE.txt contains the bundled interpreter license.\n"
    "python-packages.json records every installed distribution, version, license metadata,\n"
    "project URL, and copied license/notice file. Package license texts are under licenses/.\n"
    "Pretrained model weights are not included in this runtime.\n",
    encoding="utf-8",
)
print(json.dumps({
    "packages": [{"name": item["name"], "version": item["version"]} for item in packages],
    "inventorySha256": hashlib.sha256(inventory_bytes).hexdigest(),
}, sort_keys=True))
